### ISSUE TITLE
Review vulnerability in fastlane

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-app#1]
https://snyk.io/org/vincelee888/project/7a5dbc6d-e64a-43b7-8b43-fe86edccadc9

@fephil says we can just remove it from dependencies

**Comment by fephil** [comment]
@vincelee888 That's true and false (I should have been clearer about this when I saw the Snyk post originally). As it stands it can't be removed as fastlane is coupled into the build process. However, my opinion is that Fastlane should be installed on the developers machine with the instructions from https://docs.fastlane.tools/ as a "global" installation of sorts. Similar to npm and alike.

This ties into a broader discussion about making the app project suitable for more than one person to publish a new version/release. I don't know if you've had those discussions or you do that already. I'm currently doing this on my commercial project.

**Comment by vincelee888** [comment]
@fephil i've not touched anything to do with the app, tbh, but multiple (approved) devs being able to release betas/live sounds good to me.

@tonymcbeth - any thoughts?

**Comment by tonymcbeth** [comment]
@vincelee888 @fephil The local installation was set up so we could introduce Continuous Integration in the near future. It means that the CI agent and all developers are using the same versions of the build pipeline tools. Everything is run from a Rakefile meaning we only need Ruby and Rake installed on any dev / build machines and we could introduce other build tools in the future without altering machine setup. I personally think this is a better solution.

What exactly is the vulnerability and do we know how it will affect our codebase? I can't access the info from link you posted in the previous comment. I we feel this is a threat then we can update the build process accordingly

**Comment by tonymcbeth** [comment]
@vincelee888 @fephil i don't think removing the dependency is necessary until we understand more about the security threat and how it could impact us.

I've read a little into the issue and it looks to be around code injection and DOS attacks. Surely it wouldn't matter if the code is executed from a local dependency or a global one it's still doing the same thing? It feels like this would be a much bigger issue if this was being used as part of a web application. As i said, i've only had a quick look so may have missed something but what are your opinions on this?

@fephil feel free to @ me here or Slack (app channel) about any issues / suggestions around the app, i'm more than happy to help.

**Comment by fephil** [comment]
I don't want to bikeshed and this is your project, where as I am just an interested party. I haven't got anything more to offer at this point.

**Comment by vincelee888** [comment]
closing
