### ISSUE TITLE
Updates to the app in 2017 - initial maintenance and research

### ISSUE THREAD

**Issue by fephil** [StreetSupport/streetsupport-app#2]
Pinging @vincelee888 @vivslack 

I've had a look at the app and I think it would be worth putting in some upgrades in as there is no analytics to know how the app is performing and what people are doing within the app.

As there is no obvious app development roadmap, I propose that I action the following in priority order:

1. Add Git flow into the repo,
2. Add Google analytics to the app. This would give us combined platform analytics and user journeys. (I have an example of this I can show privately).
3. Add Sentry.JS error logging. We have no idea if the app is working on users devices as hybrid apps can "soft/non-fatal" crash but not hard crash as the app is made out of javascript.
4. Add Crosswalk for Android 4.1 - 4.4. This will enable first class support for low power devices, a priority for the potential userbase of the app.
5. Add wkwebview for IOS. Improves speed and general support for IOS devices.
6. Upgrade to latest Ionic and related plugins. 

All I'd need for the above is access to the GA account and ideally access to Google Play Store/iTunes Connect to get going with the above.

All the above work has been successfully done for the "other" app I built to good success.

Let me know your thoughts, ideally ASAP as I have a bit of time coming up.

**Comment by fephil** [comment]
As a follow on, I have the following devices so I can test the app thoroughly:

Android 4.4 Old phone
Nexus 5X
Google Pixel
iPhone 5c
iPhone 6 Plus

**Comment by vincelee888** [comment]
nice one. iProspect are handling our analytics, so I'll drop them a message as to how they want to monitor the app. i'll see what i can do about the app store accounts

**Comment by fephil** [comment]
Sorry who are iProspect?

**Comment by vincelee888** [comment]
aka dentsu - on portland st next to philpotts - they've offered to help with analytics stuff

**Comment by fephil** [comment]
Ah I see, cool.

I'd strongly push for GA as:

* It integrates well in a hybrid app (some aren't great when it's not native),
* It would work side by side with the website analytics,
* I know how to do it quickly and easily (we do some super nice tracking on the other app)

**Comment by fephil** [comment]
Just saw the email @vincelee888 ill reply with an intro/the above points.

**Comment by fephil** [comment]
I'm closing as this has been moved to trello.
